-- DARBCO Agri Workflow & Financial Processing System
-- Supabase / PostgreSQL schema
-- Run this in Supabase SQL Editor.

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS restock_requests CASCADE;
DROP TABLE IF EXISTS finance_transactions CASCADE;
DROP TABLE IF EXISTS payroll_slips CASCADE;
DROP TABLE IF EXISTS payroll_batches CASCADE;
DROP TABLE IF EXISTS arb_log_carreros CASCADE;
DROP TABLE IF EXISTS arb_logs CASCADE;
DROP TABLE IF EXISTS daily_boxes CASCADE;
DROP TABLE IF EXISTS production_records CASCADE;
DROP TABLE IF EXISTS credit_balances CASCADE;
DROP TABLE IF EXISTS stock_transactions CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS inventory_categories CASCADE;
DROP TABLE IF EXISTS beneficiaries CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(40) NOT NULL UNIQUE,
  label       VARCHAR(80) NOT NULL
);

INSERT INTO roles (code, label) VALUES
  ('manager_admin',        'Manager / Admin'),
  ('production_clerk',     'Production Clerk'),
  ('inventory_bookkeeper', 'Inventory Bookkeeper'),
  ('payroll_personnel',    'Payroll Personnel'),
  ('finance_officer',      'Finance Officer');

CREATE TABLE users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     VARCHAR(120) NOT NULL,
  username      VARCHAR(60)  NOT NULL UNIQUE,
  email         VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role_id       INTEGER NOT NULL,
  is_active     SMALLINT NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

INSERT INTO users (full_name, username, email, password_hash, role_id, is_active) VALUES
  ('DARBCO Administrator',   'admin',       'admin@darbco.local',       '$2b$10$eb.2zhwpWBr7lu2L6XGHjOXuX27LnftQtFbX990PNIpleBoqGHb5C', 1, 1),
  ('Production Clerk',       'production',  'production@darbco.local',  '$2b$10$eb.2zhwpWBr7lu2L6XGHjOXuX27LnftQtFbX990PNIpleBoqGHb5C', 2, 1),
  ('Inventory Bookkeeper',   'inventory',   'inventory@darbco.local',   '$2b$10$eb.2zhwpWBr7lu2L6XGHjOXuX27LnftQtFbX990PNIpleBoqGHb5C', 3, 1),
  ('Payroll Personnel',      'payroll',     'payroll@darbco.local',     '$2b$10$eb.2zhwpWBr7lu2L6XGHjOXuX27LnftQtFbX990PNIpleBoqGHb5C', 4, 1),
  ('Finance Officer',        'finance',     'finance@darbco.local',     '$2b$10$eb.2zhwpWBr7lu2L6XGHjOXuX27LnftQtFbX990PNIpleBoqGHb5C', 5, 1);

CREATE TABLE beneficiaries (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(20)  NOT NULL UNIQUE,
  full_name   VARCHAR(120) NOT NULL,
  block_no    VARCHAR(20)  NULL,
  contact_no  VARCHAR(40)  NULL,
  address     VARCHAR(255) NULL,
  is_active   SMALLINT NOT NULL DEFAULT 1,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO beneficiaries (code, full_name, block_no, contact_no, address) VALUES
  ('B-001', 'Roberto Cruz',       'Block 1', '09123456701', 'Panabo City, Davao del Norte'),
  ('B-002', 'Liza Mariano',       'Block 1', '09123456702', 'Panabo City, Davao del Norte'),
  ('B-003', 'Antonio Villanueva', 'Block 2', '09123456703', 'Panabo City, Davao del Norte'),
  ('B-004', 'Helena Pascual',     'Block 2', '09123456704', 'Panabo City, Davao del Norte'),
  ('B-005', 'Ferdinand Lopez',    'Block 3', '09123456705', 'Panabo City, Davao del Norte'),
  ('B-006', 'Gloria Santos',      'Block 3', '09123456706', 'Panabo City, Davao del Norte'),
  ('B-007', 'Manuel Tan',         'Block 4', '09123456707', 'Panabo City, Davao del Norte'),
  ('B-008', 'Beatrice Ong',       'Block 4', '09123456708', 'Panabo City, Davao del Norte');

CREATE TABLE inventory_categories (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code  VARCHAR(8)  NOT NULL UNIQUE,
  label VARCHAR(80) NOT NULL UNIQUE
);

INSERT INTO inventory_categories (code, label) VALUES
  ('FERT', 'Fertilizers & Soil Inputs'),
  ('CHEM', 'Chemicals & Crop Protection'),
  ('FARM', 'Farm Materials'),
  ('PACK', 'Packaging Materials'),
  ('TOOL', 'Tools & Equipment'),
  ('SEED', 'Seeds & Planting Materials'),
  ('SUPP', 'General Supplies');

CREATE TABLE inventory_items (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id   VARCHAR(20)  NOT NULL UNIQUE,
  item_name     VARCHAR(120) NOT NULL,
  category_id   INTEGER NOT NULL,
  unit          VARCHAR(20) NOT NULL DEFAULT 'kg' CHECK (unit IN ('kg','pcs','liter','pair','roll','bag','box')),
  on_hand       NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit_cost     NUMERIC(12,2) NOT NULL DEFAULT 0,
  expiry_date   DATE NULL,
  stock_date    DATE NULL,
  is_active     SMALLINT NOT NULL DEFAULT 1,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_cat FOREIGN KEY (category_id) REFERENCES inventory_categories(id)
);

CREATE TABLE stock_transactions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no    VARCHAR(40) NOT NULL UNIQUE,
  txn_type        VARCHAR(40) NOT NULL CHECK (txn_type IN ('Stock In','Cash Purchase','Credit Issued','Adjustment','Stock Out (Expired)')),
  item_id         INTEGER NOT NULL,
  quantity        NUMERIC(12,2) NOT NULL,
  unit_cost       NUMERIC(12,2) NOT NULL DEFAULT 0,
  supplier_name   VARCHAR(120) NULL,
  beneficiary_id  INTEGER NULL,
  reason          VARCHAR(255) NULL,
  recorded_by     INTEGER NOT NULL,
  txn_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_txn_item FOREIGN KEY (item_id) REFERENCES inventory_items(id),
  CONSTRAINT fk_txn_ben  FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id),
  CONSTRAINT fk_txn_user FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE INDEX idx_txn_at ON stock_transactions (txn_at);
CREATE INDEX idx_txn_type ON stock_transactions (txn_type);

CREATE TABLE credit_balances (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_no        VARCHAR(40)  NOT NULL UNIQUE,
  beneficiary_id    INTEGER NOT NULL,
  item_id           INTEGER NOT NULL,
  quantity          NUMERIC(12,2) NOT NULL,
  unit_cost         NUMERIC(12,2) NOT NULL,
  amount            NUMERIC(12,2) NOT NULL,
  remaining_balance NUMERIC(12,2) NOT NULL,
  status            VARCHAR(30) NOT NULL DEFAULT 'Outstanding' CHECK (status IN ('Outstanding','Partially Paid','Paid')),
  payroll_batch     VARCHAR(40)  NULL,
  issued_by         INTEGER NOT NULL,
  issued_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cb_ben  FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id),
  CONSTRAINT fk_cb_item FOREIGN KEY (item_id) REFERENCES inventory_items(id),
  CONSTRAINT fk_cb_user FOREIGN KEY (issued_by) REFERENCES users(id)
);

CREATE TABLE production_records (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_no       VARCHAR(40) NULL UNIQUE,
  harvest_date    DATE NULL,
  packing_date    DATE NOT NULL,
  beneficiary_id  INTEGER NOT NULL,
  harvester_name  VARCHAR(120) NULL,
  sub_code        VARCHAR(20)  NULL,
  stems_cut       INTEGER NOT NULL DEFAULT 0,
  buligs_total    INTEGER NOT NULL DEFAULT 0,
  buligs_11w      INTEGER NOT NULL DEFAULT 0,
  buligs_12w      INTEGER NOT NULL DEFAULT 0,
  buligs_13w      INTEGER NOT NULL DEFAULT 0,
  buligs_14w      INTEGER NOT NULL DEFAULT 0,
  class_a_hands   INTEGER NOT NULL DEFAULT 0,
  class_a_big_hands INTEGER NOT NULL DEFAULT 0,
  class_a_small_hands INTEGER NOT NULL DEFAULT 0,
  class_a_cps     INTEGER NOT NULL DEFAULT 0,
  class_a_sh      INTEGER NOT NULL DEFAULT 0,
  class_a_fp      INTEGER NOT NULL DEFAULT 0,
  class_b_total   INTEGER NOT NULL DEFAULT 0,
  class_b_big_hands INTEGER NOT NULL DEFAULT 0,
  class_b_small_hands INTEGER NOT NULL DEFAULT 0,
  class_b_cps     INTEGER NOT NULL DEFAULT 0,
  class_b_clb     INTEGER NOT NULL DEFAULT 0,
  class_b_h       INTEGER NOT NULL DEFAULT 0,
  class_b_i       INTEGER NOT NULL DEFAULT 0,
  class_b_d       INTEGER NOT NULL DEFAULT 0,
  special_total   INTEGER NOT NULL DEFAULT 0,
  defects_11w     INTEGER NOT NULL DEFAULT 0,
  defects_12w     INTEGER NOT NULL DEFAULT 0,
  defects_13w     INTEGER NOT NULL DEFAULT 0,
  defects_14w     INTEGER NOT NULL DEFAULT 0,
  rejects_11w     INTEGER NOT NULL DEFAULT 0,
  rejects_12w     INTEGER NOT NULL DEFAULT 0,
  rejects_13w     INTEGER NOT NULL DEFAULT 0,
  rejects_14w     INTEGER NOT NULL DEFAULT 0,
  status          VARCHAR(30) NOT NULL DEFAULT 'Submitted' CHECK (status IN ('Draft','Submitted','Returned','Verified','Used in Payroll')),
  recorded_by     INTEGER NOT NULL,
  recorded_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pr_ben  FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id),
  CONSTRAINT fk_pr_user FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE INDEX idx_pr_date ON production_records (packing_date);

CREATE TABLE daily_boxes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packing_date    DATE NOT NULL,
  first_box_at    TIME NULL,
  last_box_at     TIME NULL,
  class_a_total   INTEGER NOT NULL DEFAULT 0,
  class_b_total   INTEGER NOT NULL DEFAULT 0,
  special_total   INTEGER NOT NULL DEFAULT 0,
  recorded_by     INTEGER NOT NULL,
  recorded_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_db_user FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE INDEX idx_db_date ON daily_boxes (packing_date);

CREATE TABLE arb_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packing_date    DATE NOT NULL,
  beneficiary_id  INTEGER NOT NULL,
  block_no        VARCHAR(20) NULL,
  recorded_by     INTEGER NOT NULL,
  recorded_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_arb_ben  FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id),
  CONSTRAINT fk_arb_user FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE INDEX idx_arb_date ON arb_logs (packing_date);

CREATE TABLE arb_log_carreros (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arb_log_id    BIGINT NOT NULL,
  carrero_name  VARCHAR(120) NOT NULL,
  time_arrival  TIME NULL,
  w11           INTEGER NOT NULL DEFAULT 0,
  w12           INTEGER NOT NULL DEFAULT 0,
  w13           INTEGER NOT NULL DEFAULT 0,
  w14           INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_arbc_log FOREIGN KEY (arb_log_id) REFERENCES arb_logs(id) ON DELETE CASCADE
);

CREATE TABLE payroll_batches (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no        VARCHAR(40)  NOT NULL UNIQUE,
  period_start    DATE NOT NULL,
  period_end      DATE NOT NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Submitted','Validated','Returned','Approved','Rejected','Released')),
  prepared_by     INTEGER NOT NULL,
  validated_by    INTEGER NULL,
  validated_at    TIMESTAMP NULL,
  approved_by     INTEGER NULL,
  approved_at     TIMESTAMP NULL,
  return_reason   VARCHAR(255) NULL,
  total_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_pb_prep FOREIGN KEY (prepared_by) REFERENCES users(id),
  CONSTRAINT fk_pb_val  FOREIGN KEY (validated_by) REFERENCES users(id),
  CONSTRAINT fk_pb_app  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE payroll_slips (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slip_no           VARCHAR(40) NULL UNIQUE,
  batch_id          BIGINT NOT NULL,
  beneficiary_id    INTEGER NOT NULL,
  production_record_id BIGINT NULL,
  payroll_period    VARCHAR(80) NULL,
  harvest_date      DATE NULL,
  class_a_boxes     INTEGER NOT NULL DEFAULT 0,
  class_b_boxes     INTEGER NOT NULL DEFAULT 0,
  special_boxes     INTEGER NOT NULL DEFAULT 0,
  class_a_price     NUMERIC(12,2) NOT NULL DEFAULT 0,
  class_b_price     NUMERIC(12,2) NOT NULL DEFAULT 0,
  special_price     NUMERIC(12,2) NOT NULL DEFAULT 0,
  material_deduction NUMERIC(12,2) NOT NULL DEFAULT 0,
  previous_balance  NUMERIC(12,2) NOT NULL DEFAULT 0,
  labor_cost        NUMERIC(12,2) NOT NULL DEFAULT 0,
  other_deductions  NUMERIC(12,2) NOT NULL DEFAULT 0,
  gross_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
  credit_deduction  NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_deductions  NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_ps_batch FOREIGN KEY (batch_id) REFERENCES payroll_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_ps_ben   FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id),
  CONSTRAINT fk_ps_prod  FOREIGN KEY (production_record_id) REFERENCES production_records(id)
);

CREATE TABLE finance_transactions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no  VARCHAR(40) NOT NULL UNIQUE,
  txn_date      DATE NOT NULL,
  category      VARCHAR(80) NOT NULL,
  description   VARCHAR(255) NOT NULL,
  amount        NUMERIC(14,2) NOT NULL,
  direction     VARCHAR(3) NOT NULL CHECK (direction IN ('IN','OUT')),
  recorded_by   INTEGER NOT NULL,
  CONSTRAINT fk_ft_user FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE TABLE restock_requests (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_no      VARCHAR(40) NOT NULL UNIQUE,
  item_id         INTEGER NOT NULL,
  quantity        NUMERIC(12,2) NOT NULL,
  requested_by    INTEGER NOT NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected','Fulfilled')),
  reviewed_by     INTEGER NULL,
  requested_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at     TIMESTAMP NULL,
  notes           VARCHAR(255) NULL,
  CONSTRAINT fk_rr_item FOREIGN KEY (item_id) REFERENCES inventory_items(id),
  CONSTRAINT fk_rr_req  FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_rr_rev  FOREIGN KEY (reviewed_by)  REFERENCES users(id)
);

CREATE TABLE audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL,
  module      VARCHAR(60)  NOT NULL,
  action      VARCHAR(60)  NOT NULL,
  target_type VARCHAR(60)  NULL,
  target_id   VARCHAR(60)  NULL,
  details     TEXT         NULL,
  ip_address  VARCHAR(45)  NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_al_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_al_created ON audit_logs (created_at);

-- Test accounts. All passwords are: password
-- admin@darbco.local, production@darbco.local, inventory@darbco.local,
-- payroll@darbco.local, finance@darbco.local
